### ISSUE TITLE
Blueprint Assignment IaC Issue

### ISSUE THREAD

**Issue by dutysm** [Azure/azure-blueprints#60]
I am having issue with assigning blueprint to subscription thru bicep.  Following is the bicep I'm using.  I'm using system assigned identity, we don't want to not use user managed identity

```
resource assignment 'Microsoft.Blueprint/blueprintAssignments@2018-11-01-preview' = {
  name: name
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    displayName: displayName
    blueprintId: blueprintVersionId
    scope: scope
    resourceGroups: {}
    parameters: {
      resourceLocation : {
        value: location
      }     
    }
    locks: {
      mode: 'None'
    }
  }
}
```

Following is the error I receive:

`Exceeded maximum wait time of '00:05:00'. Message: 'Either the Azure Blueprints service principal does not have owner permissions on the target subscription, or the system-assigned managed identity has not yet finished replicating.'.`

Blueprint assignment using system assigned works with no problem from the portal.  But,  I need to this to work from code.

The error says identity may not be finished replicating.  How do I implement wait time for it?

**Comment by dutysm** [comment]
@alex-frankel 
Please see the issue I reported.  Also, what is the status of deployment stack release?

**Comment by raeder1986** [comment]
Seems that problem is still relevant - got the same deploying Blueprint using Azure Cli (updating existing assignment). Solved manually granting owner rights to Azure Blueprints SP:
- get Azure Blueprints SP Id
`az ad sp show --id f71766dc-90d9-4b7d-bd9d-4499c4331c3f --query "id"`
- get your subscription id (choose needed from list)
`az account list --query "[].{name:name, id:id}" --output tsv`
- grant owner permissions
`az role assignment create --assignee "_Blueprints_SP_Id_" --role "Owner" --subscription "_Subscription_Id_"`
After procedure I made assignment update from Azure Cli work again.
